const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#0a0a0a",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    cardElevated: "#fafafa",
    primary: "#0a0a0a",
    primaryForeground: "#ffffff",
    secondary: "#f4f4f5",
    secondaryForeground: "#18181b",
    muted: "#f4f4f5",
    mutedForeground: "#71717a",
    accent: "#fafafa",
    accentForeground: "#18181b",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    success: "#16a34a",
    border: "#e4e4e7",
    borderStrong: "#d4d4d8",
    input: "#e4e4e7",
    overlay: "rgba(10,10,10,0.55)",
    mapSurface: "#f1f3f4",
    mapStroke: "#dfe2e6",
  },
  dark: {
    text: "#fafafa",
    tint: "#fafafa",
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#161616",
    cardForeground: "#fafafa",
    cardElevated: "#1c1c1c",
    primary: "#fafafa",
    primaryForeground: "#0a0a0a",
    secondary: "#1c1c1c",
    secondaryForeground: "#fafafa",
    muted: "#1c1c1c",
    mutedForeground: "#a1a1aa",
    accent: "#1c1c1c",
    accentForeground: "#fafafa",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    border: "#262626",
    borderStrong: "#3f3f46",
    input: "#262626",
    overlay: "rgba(0,0,0,0.7)",
    mapSurface: "#161616",
    mapStroke: "#262626",
  },
  radius: 14,
};

export default colors;
