kind = "mobile"
previewPath = "/"
title = "Thikana"
version = "1.0.0"
id = "artifacts/thikana"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19023

[services.development]
run = "pnpm --filter @workspace/thikana run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/thikana", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/thikana", "run", "serve" ]

[services.env]
PORT = "19023"
BASE_PATH = "/"
